// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdzydvomvwttkegnpyhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtkenlkdm9tdnd0dGtlZ25weWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMTAzNTMsImV4cCI6MjA3MTU4NjM1M30.sMyJ1B6jOfMbDavkuC-v3IBEDzMvPkSoz0tSrCtGW6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});